#!/usr/bin/python


def inv_cdp(info, params):

    node = inv_tree("networking.neighbors:")
    
    local_if, remote_if = info

    if_dict={}
    
    for l_if_id,l_if_name in local_if:

        for  r_if_id, r_device, r_port in remote_if:
            if r_if_id.split(".")[:1][0] == l_if_id:
                node.append({
                  "l_if_name" : l_if_name,
                  "r_device"  : r_device,
                  "r_if_name" : r_port,
                  "r_if_mac"  : "",
                  "r_if_desc" : "",

                })

inv_info["inv_cdp"] = {
                        "inv_function" : inv_cdp,
                        "snmp_info"    : [( ".1.3.6.1.2.1.2.2.1", [ "1",            # ifIndex
                                                                    "2",            # ifDescr
                                         ]),
                                          (".1.3.6.1.4.1.9.9.23.1.2.1.1", [OID_END,  # if string
                                                                          "6", # remote device name
                                                                          "7", # remote device port 
                                         ]),
                                         ],
                  "snmp_scan_function" : lambda oid: oid(".1.3.6.1.4.1.9.9.23.*") != None,
                     }
