#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#################################################################
#---------------------------------------------------------------#
# Author: Markus Weber                                          #
# Contact: markus.weber@lfst.bayern.de                          #
# License: GPL                                                  #
# File: jolokia_generic                                         #
# Version: 2.1.1                                                #
# Revision: 03.11.2014                                          #
# Description: This Check allows to monitor any given           #
#  MBean/Attribute of an Application server.                    #
#################################################################

# Sample output
# <<<jolokia_generic>>>
# 8080,/pwm,LoginServlet generic.rate.errorPerRequest.requestCount 878
# 8080,/pwm,LoginServlet generic.rate.errorPerRequest.errorCount 0
# 8080,/pwm,LogoutServlet generic.rate.errorPerRequest.requestCount 1
# 8080,/pwm,LogoutServlet generic.rate.errorPerRequest.errorCount 0
# 8080,/pwm,LogoutServlet generic.gauge.countAllocated 0
# dmst1c00s00,dmst1c00s00 generic.gauge.JDBCConStatistic.CurrCapacityHighCount 1
# dmst1c00s00,dmst1c00s00 generic.gauge.JDBCConStatistic.ActiveConnectionsCurrentCount 0
# dmst1c00s00,dmst1c00s00 generic.gauge.JDBCConStatistic.CurrCapacity 1
# dmst1c00s00,dmst1c00s00 generic.gauge.JDBCConErrors.WaitingForConnectionFailureTotal 0
# dmst1c00s00,dmst1c00s00 generic.gauge.JDBCConErrors.WaitSecondsHighCount 0
# dmst1c00s00,dmst1c00s00 generic.gauge.JDBCConErrors.LeakedConnectionCount 0
# dmst1c00s00,dmst1c00s00 generic.string.JDBC_Status.State Running


# Default levels for low warn, low crit, high warn, high crit and a empty list for string mode
factory_settings["jolokia_generic_default_levels"] = { "levels" : (-1.0, -1.0, 0.0, 0.0), "expectedStrings" : [] }

def inventory_jolokia_generic(info):
    inv = []
    parsed = jolokia_metrics_parse(info)

    for inst, vals in parsed.items():
        for app, appstate in vals.get('apps', {}).items():
            if 'servlets' in appstate:
                for servlet in appstate['servlets']:
                    #for Attribute in appstate['servlets'][servlet]:
                    for key in appstate['servlets'][servlet]:
                            if key.startswith("generic."):
                                keyparts = key.split(".")
                                if (len(keyparts) == 4 or len(keyparts) == 3) and ('%s %s %s %s' % (inst, app, servlet, keyparts[2]), {}) not in inv:
                                        inv.append( ('%s %s %s %s' % (inst, app, servlet, keyparts[2]), {} ) )
                                else:
                                    continue

            for key in appstate:
                if key.startswith("generic."):
                    keyparts = key.split(".")
                    if (len(keyparts) == 3 or len(keyparts) == 4) and ('%s %s %s' % (inst, app, keyparts[2]), {}) not in inv:
                        # keyparts[2] is either the attribute or the grouping name for rate and gauge values
                        inv.append( ('%s %s %s' % (inst, app, keyparts[2]), {} ) )
                    else:
                        continue

        for key in vals:
            if key.startswith("generic."):
                keyparts = key.split(".")
                if (len(keyparts) == 4 or len(keyparts) == 3) and ('%s %s' % (inst, keyparts[2]), {}) not in inv:
                    inv.append( ('%s %s' % (inst, keyparts[2]), {} ) )
                else:
                    continue
    return inv

def check_jolokia_generic(item, params, info):
    import re
    parsed = jolokia_metrics_parse(info)
    itemParts = item.split()
    output, perf, status, workvalues, workitems, workmodes = "", [], 0, [], [], []

    if len(itemParts) == 4:
        if itemParts[2] in parsed[itemParts[0]]['apps'][itemParts[1]]['servlets']:
            base = parsed[itemParts[0]]['apps'][itemParts[1]]['servlets'].get( itemParts[2], {} )
    elif len(itemParts) == 3:
        if itemParts[1] in parsed[itemParts[0]]['apps']:
            base = parsed[itemParts[0]]['apps'].get( itemParts[1], {} )
    elif len(itemParts) == 2:
        if itemParts[0] in parsed:
            base = parsed.get( itemParts[0], {} )
    else:
        base = {}

    for key in base:
        if key.startswith("generic.rate." + itemParts[-1]):
            workmodes.append('rate')
            workvalues.append(savefloat(base[key]))
        elif key.startswith("generic.gauge." + itemParts[-1]):
            workmodes.append('gauge')
            workvalues.append(savefloat(base[key]))
        elif key.startswith("generic.string." + itemParts[-1]):
            workmodes.append('string')
            workvalues.append(base[key])
        else:
            continue
        workitems.append(key.split('.')[-1])

    if workmodes[0] == 'gauge':
        for i in range(len(workitems)):
            if workitems[i] in params:
                lo_warn, lo_crit, hi_warn, hi_crit = params[workitems[i]]
            else:
                lo_warn, lo_crit, hi_warn, hi_crit = params["levels"] 

            if lo_crit is not None and workvalues[i] <= lo_crit:
                status = 2
                output += "%s is %s (!!); " % (workitems[i], workvalues[i])

            elif lo_warn is not None and workvalues[i] <= lo_warn:
                status = 1
                output += "%s is %s (!); " % (workitems[i], workvalues[i])

            elif hi_crit is not None and hi_crit != 0.0 and workvalues[i] >= hi_crit:
                status = 2
                output += "%s is %s (!!); " % (workitems[i], workvalues[i])

            elif hi_warn is not None and hi_warn != 0.0 and workvalues[i] >= hi_warn:
                status = 1
                output += "%s is %s (!); " % (workitems[i], workvalues[i])

            else:
                output += "%s is %s; " % (workitems[i], workvalues[i])

            perf.append((workitems[i], workvalues[i]))

    elif workmodes[0] == 'string':
        for i in range(len(workitems)):
            regexes = []
            if len(params["expectedStrings"]) != 0:
                for j in params["expectedStrings"]:
                    regexes.append(re.compile(j))

                if not any(regex.match(workvalues[i]) for regex in regexes):
                    status = 2
                    output += "%s is %s (!!); " % (workitems[i], workvalues[i])
                else:
                    output += "%s is %s; " % (workitems[i], workvalues[i])
            else:
                output += "%s is %s; " % (workitems[i], workvalues[i])
    else:
        if len(workitems) == 1:
            if workitems[0] in params:
                lo_warn, lo_crit, hi_warn, hi_crit = params[workitems[0]]
            else:
                lo_warn, lo_crit, hi_warn, hi_crit = params["levels"] 

            # rate per minute
            timedif, rate = get_counter( "jolokia_generic.%s" % (itemParts[-1]), time.time(), savefloat(workvalues[0]) )
            rate = rate * 60.0

            if lo_crit is not None and rate <= lo_crit:
                status = 2
                output += "%.2f %s/min (!!) with a total of %.2f" % (rate, workitems[0], savefloat(workvalues[0]))

            elif lo_warn is not None and rate <= lo_warn:
                status = 1
                output += "%.2f %s/min (!) with a total of %.2f" % (rate, workitems[0], savefloat(workvalues[0]))

            elif hi_crit is not None and hi_crit != 0.0 and rate >= hi_crit:
                status = 2
                output += "%.2f %s/min (!!) with a total of %.2f" % (rate, workitems[0], savefloat(workvalues[0]))

            elif hi_warn is not None and hi_warn != 0.0 and rate >= hi_warn:
                status = 1
                output += "%.2f %s/min (!) with a total of %.2f" % (rate, workitems[0], savefloat(workvalues[0]))

            else:
                output += "%.2f %s/min with a total of %.2f" % (rate, workitems[0], savefloat(workvalues[0]))

            perf.append( (workitems[0], rate) )
        elif len(workitems) == 2:
            lo_warn, lo_crit, hi_warn, hi_crit = params["levels"] 

            if workvalues[0] == 0 and workvalues[1] == 0:
                rate = 0
                output += "The rate of %s / %s = %.2f" % (workitems[1], workitems[0], rate)
                perf.append( ("%sPER%s" % (workitems[1], workitems[0]), rate) )
            elif workvalues[0] > workvalues[1]:
                # rate of 2 values 
                rate = savefloat(workvalues[1])/savefloat(workvalues[0])
                output += "The rate of %s / %s = %.2f" % (workitems[1], workitems[0], rate)
                perf.append( ("%sPER%s" % (workitems[1], workitems[0]), rate) )
            else:
                # rate of 2 values reverse
                rate = savefloat(workvalues[0])/savefloat(workvalues[1])
                output += "The rate of %s / %s = %.2f" % (workitems[0], workitems[1], rate)
                perf.append( ("%sPER%s" % (workitems[0], workitems[1]), rate) )

            if lo_crit is not None and rate <= lo_crit:
                status = 2
            elif lo_warn is not None and rate <= lo_warn:
                status = 1
            elif hi_crit is not None and hi_crit != 0.0 and rate >= hi_crit:
                status = 2
            elif hi_warn is not None and hi_warn != 0.0 and rate >= hi_warn:
                status = 1
        else:
            status = 3
            output += "something went wrong! Found more then 2 values in rate mode."
    return (status, output, perf)

check_info["jolokia_generic"] = {
    "service_description"     : "JVM %s",
    "check_function"          : check_jolokia_generic,
    "inventory_function"      : inventory_jolokia_generic,
    "default_levels_variable" : "jolokia_generic_default_levels",
    "group"                   : "jvm_generic",
    "includes"                : [ "jolokia_metrics" ],
    "has_perfdata"            : True,
}
