#!/bin/sh
#
# Author: Matthias Henze matthias@mhcsoftware.de
#
#
# nfsperf is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.
#
# nfsperf collets NFS performance data


mount | grep nfs >/dev/null 2>&1
if [ $? -eq 0 ]
then
	echo "<<<nfsperf>>>"
	cat /proc/self/mountstats | awk -- '
BEGIN { N=0 }
/^device .* (nfs|nfs[0-9]) / { N=N+1; mp[N] = $2 } 
/bytes:/ { bytes[N] = $0 }
/events:/ { events[N] = $0 }
/READ:/ { read[N] = $0}
/WRITE:/ { write[N] = $0 }
END {
for ( i=1; i<=N; i++ ) {
   printf("%s %s %s %s %s\n", mp[i], bytes[i], events[i], read[i], write[i])
}
}
' | sed 's/bytes://;s/events://;s/READ://;s/WRITE://;s/\t/ /g' | sed 's/\( \)*/\1/g' 
fi

